dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7"
  - "3.8-dev"  # 3.8 development branch
  - "pypy3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install pytest"
  - "pip install pytest-cov"
  - "pip install coveralls"
  - "pip install ."
script:
    coverage run --source treemaker -m py.test
after_success:
    coveralls
